version: "3.7"

services:
  redis:
    image: redis:alpine
    container_name: redis-experiment
    restart: always
    ports:
      - 6379:6379
  postgres:
    image: postgres:12
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - TZ=Etc/UTC
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ace
      - PGDATA=/var/lib/postgresql/data/db-files/
  worker:
    image: celery-experiment
    command:
      [
        "watchmedo",
        "auto-restart",
        "--directory=./",
        "--pattern=*.py",
        "--recursive",
        "--",
        "celery",
        "-A",
        "tasks.app",
        "worker",
        "--loglevel=info",
      ]
    volumes:
      - ./:/app
    depends_on:
      - server
  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: celery-experiment
    container_name: celery-fastapi-server
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - redis
      - postgres
    volumes:
      - ./:/app
    env_file:
      - .env

    command:
      ["uvicorn", "api:app", "--port", "8000", "--host", "0.0.0.0", "--reload"]
